### ISSUE TITLE
[Question] Wrapping monad with macros the right way

### ISSUE THREAD

**Issue by caioaao** [nubank/state-flow#120]
Is there a right way to do that? For instance, suppose I want to change a monadic function to get the output string when it runs. I implemented it this way:

```clojure
(defn wrap-with-out-str [f]
  (fn [& args] (with-out-str (apply f args))))

(defn m-with-out-str [mv]
  (update mv :mfn wrap-with-out-str))

;; Usage
(-> (state/wrap-fn #(print "yo"))
    m-with-out-str
    state-flow/run) ;=> "yo"
```
Am I doing it right? Feels wrong to access `:mfn` here, but I don't know if there's a right approach to this. 

Just as a side note: my use case is using [nubank/mockfn](https://github.com/nubank/mockfn) macros with state-flow

**Comment by sovelten** [comment]
See https://github.com/nubank/state-flow/pull/33 for some discussions about it.

My suggestion is to avoid macros whenever possible because they ~are~ can be evil

This is how we made a wrapper for with-redefs:

```clojure
(defmacro with-redefs
  [bindings flow]
  `(m/do-let
    [world#  (state/get)
     runner# (state-flow/runner)
     :let [[ret# state#] (clojure.core/with-redefs ~bindings
                           (runner# ~flow world#))]]
    (state/put state#)
    (state/return ret#)))
```

We don't want to make this kind of thing available in the library because there is a lot of potential for misuse.

**Comment by caioaao** [comment]
Nice. I agree about the danger of misuse too, but might be ok to add it under `labs` ns maybe? My guess is it's already being re-implemented in the wild, so at least it'd be available if one digs deep enough

**Comment by sovelten** [comment]
Yeah, I think it would be fine in the labs, with a huge warning though

**Comment by dchelimsky** [comment]
> Just as a side note: my use case is using nubank/mockfn macros with state-flow

Are you using a component system? If so, could you create a stub version of a component instead of using the dark magic of mockfn?

**Comment by sovelten** [comment]
> > Just as a side note: my use case is using nubank/mockfn macros with state-flow
> 
> Are you using a component system? If so, could you create a stub version of a component instead of using the dark magic of mockfn?

Yeah, the problem

**Comment by caioaao** [comment]
@dchelimsky sort of. I'm mocking the api of a second micro-service that's not implemented, so basically I currently have have this:

```clojure
(ns service-a.ports.service-b)

(defn call! [args]
  (throw (java.lang.UnsupportedOperationException.
          "service-b is not implemented yet")))
```

And I need to mock what `call!` would return in this case. So I could turn `ports.service-b` into a component and have `call!` be a method of this component, but I think this should be an anti-pattern IMO

@sovelten we can go one step further and only enable it if a global `*enable-flow-redefs-macro*` flag is set to true, and throw an exception otherwise. that should be enough to discourage its misuse

**Comment by caioaao** [comment]
Just expanding on the "anti-pattern" argument: stuartsierra's component (and arguably its alternatives) states its purpose as "'Component' is a tiny Clojure framework for managing the lifecycle and dependencies of software components __which have runtime state__." . My `ports.service-b` implementation doesn't have a runtime state outside of the tests (and inside tests the runtime state would be the mock info set by the flow - not really a state required by the implementation/business logic). 

Another issue is if I use a component mock I'd have to re-implement some useful functionality from mockfn, like verify if the argument matches the mock, track call count, etc

Also I feel using components for dependency injection is kind of heavy on the OOP mindset and I'd go with the LISP-y way here and rely on the macro system.

**Comment by caioaao** [comment]
opened #123 with @sovelten 's snippet and a feature flag

**Comment by dchelimsky** [comment]
Resolved by https://github.com/nubank/state-flow/pull/123
