### ISSUE TITLE
A flow using swap-state does not eval to [<return-value><new-state>]?

### ISSUE THREAD

**Issue by fdserr** [nubank/state-flow#140]
Hello,

thanks for the great lib.

The README says: 
```
You can think flows and the steps within them as functions of the state, e.g.

(fn [<state>] [<return-value>, <possibly-updated-state>])
```

Is swap-state an exception?
```
(flow/run* ; omitted init, assuming state holds a Datomic conn
  (flow "swap" (flow/swap-state (fn [state] @(d/transact (:conn state) [...]) {:res :ok})))
; => [{:conn ...} {:res :ok}]
```

I'm getting the state in place of `<return-value>`, and the application result in place of `<possibly-updated-state>`.

What am I doing wrong?

TIA

**Comment by dchelimsky** [comment]
You're not doing anything wrong. The [doc for `swap-state`](https://cljdoc.org/d/nubank/state-flow/5.6.1/api/state-flow.api#swap-state) says "Creates a flow that replaces state with the result of applying f to state with any additional args.". What's missing is that the `return-value` is the unmodified state, though that is described [here](https://github.com/nubank/state-flow/blob/987f48cd8c4b62da598a0febcb5f4f9298526fe6/doc/walkthrough.repl#L148-L149).

I added an issue to update the doc: https://github.com/nubank/state-flow/issues/141. Closing this one.

**Comment by fdserr** [comment]
Thanks for the precision. I'll use `return` instead, though it doesn't get a chance to lookup into state to build its value. Any chance to have an extra arity with the state? (that goes thru unmodified by `return`'s body)

**Comment by dchelimsky** [comment]
Use `get-state` and bindings for that:

```clojure
(flow/run* {,,,}
  [conn (flow/get-state :conn)]
  (flow/return <,,, something with conn ,,,>))
```

Make sense?

**Comment by fdserr** [comment]
Deffo. Thanks!
