### ISSUE TITLE
Decouple assertions from reporting

### ISSUE THREAD

**Issue by dchelimsky** [nubank/state-flow#83]
* update assertions so they store pass/fail information somewhere but don't report it directly through clojure.test
* enhance runner to support reading pass/fail information and reporting it to arbitrary test runners e.g. clojure.test, midje, other

This would allow us (or others) to extend state-flow to use other test libraries

**Comment by sovelten** [comment]
I don't think I understand the part of enhancing the runner. Since the return value of the run already contains test results, then it is just data, no need for a different runner. Unless you are talking about some sort of real time feedback while the flow is running.

**Comment by dchelimsky** [comment]
> I don't think I understand the part of enhancing the runner. Since the return value of the run already contains test results, then it is just data, no need for a different runner. Unless you are talking about some sort of real time feedback while the flow is running.

@sovelten feedback in general. Real time feedback for developers working in a REPL, program feedback for devs or programs running the test suite from a shell (so a program can know pass/fail status, etc).

**Comment by sovelten** [comment]
done on https://github.com/nubank/state-flow/pull/70
